kind: Deployment
apiVersion: apps/v1
metadata:
  name: betterdev
  namespace: opty
  labels:
    app: betterdev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: betterdev
  template:
    metadata:
      labels:
        app: betterdev
        name: betterdev
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: "quay.io/yeospace/betterdev:7e0df43ee91ba2f9c90deff1dc82bb4c48b16ac3"
        imagePullPolicy: Always
        name: betterdev
        ports:
        - containerPort: 1605
        env:
          - name: MONGO_URI
            value: "mongodb://10.2.0.20:27017"
          - name: AWS_REGION
            value: us-west-2
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: betterdev
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: betterdev
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            value: us-west-2
